version: '2'
services:
    memcache:
        image: memcached:1.4.35-alpine
        restart: always
    opencart:
        image: registry.aliyuncs.com/syncxplus/php:5.6.30
        restart: always
        ports:
            - '80:80'
        volumes:
            - ./upload:/var/www/html
        links:
            - memcache:memcache
        depends_on:
            - memcache
    pure-ftpd:
        image: stilliard/pure-ftpd:hardened
        restart: always
        ports:
            - '21:21'
            - '30000-30100:30000-30100'
        environment:
            - PUBLICHOST=${PUBLIC_IP}
        volumes:
            - ./upload:/home/ftpusers/www
            - ./upload/image/catalog/onlymaker:/home/ftpusers/onlymaker